spring.application.name=service-product
spring.config.import=nacos:${spring.application.name}

server.port=9001
spring.cloud.nacos.server-addr=127.0.0.1:8848

spring.cloud.sentinel.transport.dashboard= localhost:8080
spring.cloud.sentinel.eager=true